[package]
name = "custodian_server"
version = "0.1.0"
authors = ["nubis <yo@nubis.im>"]

[dependencies]
libc = "0.2.40"
rocket = "0.3.10"
rocket_codegen = "0.3.10"
mock_derive = "0.7.0"
ctrlc = "3.1.0"
bitprim = { path = "/home/werner/bitprim-rust" }

[build-dependencies]
regex = "1.0"
