version: 2
jobs:
  build:
    docker:
      - image: wernerae/custodian_server:latest
    steps:
      - checkout
      - run: ./prepare_tests.sh
      - run: ./use_prepared_database.sh
      - run: ./run_tests.sh goes_through_the_full_wallet_lifecycle